version: '3.8'

services:
  geoService:
    build:
      context: ./geolocationService
    ports:
      - "8001:8000" # Первый сервис будет доступен на порту 8001
    depends_on:
      - db1

  db1:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7243
      POSTGRES_DB: geoService
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  usersService:
    build:
      context: ./usersService
    ports:
      - "8000:8000" # Второй сервис будет доступен на порту 8002
    depends_on:
      - db2

  db2:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7243
      POSTGRES_DB: usersService
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data1:
  postgres_data2:
