"""user model additions

Revision ID: 1c97cfdde7e0
Revises: 184d5f99c369
Create Date: 2024-12-03 14:58:48.144166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c97cfdde7e0"
down_revision: Union[str, None] = "184d5f99c369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("birth_date", sa.DateTime(), nullable=True))
    op.add_column("Users", sa.Column("about_me", sa.String(), nullable=True))
    op.add_column("Users", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Users", "last_seen")
    op.drop_column("Users", "about_me")
    op.drop_column("Users", "birth_date")
    # ### end Alembic commands ###
