"""fucking migrations

Revision ID: 262201b6bf9a
Revises: 
Create Date: 2024-12-03 16:31:09.051483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "262201b6bf9a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Conversations",
        sa.Column("last_message_date", sa.DateTime(), nullable=True),
        sa.Column("last_message_text", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Friendships",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("friend_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["friend_id"],
            ["Users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Messages",
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["Conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_user_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("users", sa.Integer(), nullable=False),
        sa.Column("conversations", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversations"],
            ["Conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "users", "conversations", name="inx_unique_user_conversation"
        ),
    )
    op.add_column("Users", sa.Column("birth_date", sa.DateTime(), nullable=True))
    op.add_column("Users", sa.Column("about_me", sa.String(), nullable=True))
    op.add_column("Users", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Users", "last_seen")
    op.drop_column("Users", "about_me")
    op.drop_column("Users", "birth_date")
    op.drop_table("conversation_user_association")
    op.drop_table("Messages")
    op.drop_table("Friendships")
    op.drop_table("Conversations")
    # ### end Alembic commands ###
