"""user model additions

Revision ID: 652bc7140f5e
Revises: 184d5f99c369
Create Date: 2024-12-03 14:04:55.863601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "652bc7140f5e"
down_revision: Union[str, None] = "184d5f99c369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("Users", sa.Column("birth_date", sa.DateTime(), nullable=True))
    op.add_column("Users", sa.Column("about_me", sa.String(), nullable=True))
    op.add_column("Users", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Users", "last_seen")
    op.drop_column("Users", "about_me")
    op.drop_column("Users", "birth_date")
    op.drop_column("Users", "created_at")
    # ### end Alembic commands ###
